#!/usr/bin/php
<?php

	function ___respawn()
	{
		echo ob_get_clean() . "\n";
		$error = error_get_last();
		if ($error['type'] == E_ERROR) {
			passthru(__FILE__);
		}
	}

	register_shutdown_function('___respawn');

	$_SERVER['DOCUMENT_ROOT']  = dirname(__FILE__);
	$_SERVER['REQUEST_URI']    = '/';
	$_SERVER['REQUEST_METHOD'] = 'GET';

	$_GET['request_format']    = 'console';

	include 'includes/init.php';

	function get($url, $params = array()) {
		$request_info = parse_url($url);
		if (isset($request_info['host'])) {
			$_SERVER['SERVER_NAME'] = $request_info['host'];
		}
		if (isset($request_info['path'])) {
			$_SERVER['REQUEST_URI'] = $request_info['path'];
		}
		$_SERVER['REQUEST_METHOD'] = 'GET';
		$_GET                      = $params;
		include 'includes/routing.php';
		exit();
	}

	fCore::enableErrorHandling('php://stdout');
	fCore::enableExceptionHandling('php://stdout');

	$___stdin   = fopen('php://stdin', 'r');
	$___depth   = 0;
	$___command = '';

	do {

		$___command = trim($___command);

		if ($___command) {
			$___echar = substr($___command, strlen($___command) - 1);

			switch ($___echar) {
				case '{':
					$___depth++;
					break;
				case '}':
					$___depth--;
					break;
			}

			if ($___depth == 0 && ($___echar == '}' || $___echar == ';')) {
				ob_start();
				try {
					eval($___command);
				} catch (Exception $___e) {
					echo fHTML::decode($___e);
				}
				$___command = '';
				if($___output = ob_get_clean()) {
					echo $___output;
					echo "\n";
				}
			}
		}
		echo '[' . getcwd() . ']# ';
	} while(($___command .= fgets($___stdin)));

